### GET request to example server
GET http://localhost:8080/api/rewards?gateDetailsIds=55afed90-e081-11f0-a6e8-0a0027000013&gateDetailsIds=55b004a6-e081-11f0-a6e8-0a0027000013
Content-Type: application/json

###